#!/usr/bin/env bash
# Dynamic HPC setup for FineTuningMaster.
#
# All machine-specific locations come from environment variables or paths.env.
# No cluster account, home directory, scratch mount, or repository path is
# embedded in the runtime layout.
#
# Usage:
#   SCRATCH_ROOT=/cluster/project/ftm bash setup_hpc.sh
#   bash setup_hpc.sh --skip-kb --skip-preflight
#
# Generated environment file:
#   ${SCRATCH_ROOT}/hpc_env.sh
#
# Later:
#   source ${SCRATCH_ROOT}/hpc_env.sh
#   sbatch experiments/slurm/job_final_matrix.sh

set -euo pipefail

PROJECT_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "${PROJECT_ROOT}"

PATHS_FILE="${PATHS_FILE:-paths.env}"
TORCH_CUDA_INDEX="${TORCH_CUDA_INDEX:-cu124}"
PYTHON_BIN="${PYTHON_BIN:-python3}"
SKIP_KB=0
SKIP_PREFLIGHT=0

usage() {
  cat <<'USAGE'
Usage: bash setup_hpc.sh [options]

Options:
  --skip-kb          Do not build scratch KB chunks.jsonl
  --skip-preflight   Do not run release preflight
  --paths-file FILE  Load per-machine paths before setup
  -h, --help         Show this help

Environment overrides:
  SCRATCH_ROOT       Root for venv, caches, models, KB and results.
                     Defaults to BIG, then XDG cache, then ~/.cache.
  VENV_DIR           Python environment (default: $SCRATCH_ROOT/venv)
  RESULTS_ROOT       Result root (default: $SCRATCH_ROOT/results)
  MODELS_DIR         Hugging Face model store (default: $SCRATCH_ROOT/models)
  CACHE_ROOT         Runtime/pip/cache root (default: $SCRATCH_ROOT/cache)
  KB_ROOT            Generated RAG KB root (default: $SCRATCH_ROOT/kb)
  TORCH_CUDA_INDEX   PyTorch index suffix (default: cu124)
  PYTHON_BIN         Python executable (default: python3)
  HF_TOKEN           Required for gated models
  ALLOW_REPO_OUTPUTS Set 1 only when intentionally writing byproducts in repo
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --skip-kb) SKIP_KB=1; shift ;;
    --skip-preflight) SKIP_PREFLIGHT=1; shift ;;
    --paths-file) [[ $# -ge 2 ]] || { echo "ERROR: --paths-file needs a value." >&2; exit 1; }; PATHS_FILE="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "ERROR: unknown argument: $1" >&2; usage; exit 1 ;;
  esac
done

# Reuse the same path-file semantics as run_experiment.sh/bootstrap_remote.sh.
# shellcheck source=scripts/lib/paths.sh
source "${PROJECT_ROOT}/scripts/lib/paths.sh"
load_paths_file "${PROJECT_ROOT}" "${PATHS_FILE}" || exit 1

case "${TORCH_CUDA_INDEX}" in
  cu118|cu124|cu126) ;;
  *) echo "ERROR: PyTorch 2.6.0 supports cu118, cu124 or cu126; got '${TORCH_CUDA_INDEX}'." >&2; exit 1 ;;
esac

resolve_path() {
  paths_resolve "${PROJECT_ROOT}" "$1"
}

SCRATCH_ROOT="${SCRATCH_ROOT:-${FTM_SCRATCH_ROOT:-${BIG:-}}}"
if [[ -z "${SCRATCH_ROOT}" ]]; then
  SCRATCH_ROOT="${XDG_CACHE_HOME:-${HOME}/.cache}/finetuningmaster"
fi
SCRATCH_ROOT="$(resolve_path "${SCRATCH_ROOT}")"

VENV_DIR="${VENV_DIR:-${VENV_PATH:-${SCRATCH_ROOT}/venv}}"
RESULTS_ROOT="${RESULTS_ROOT:-${HPC_RESULTS_ROOT:-${RESULTS_PATH:-${SCRATCH_ROOT}/results}}}"
MODELS_DIR="${MODELS_DIR:-${HPC_MODELS_DIR:-${SCRATCH_ROOT}/models}}"
CACHE_ROOT="${CACHE_ROOT:-${HPC_CACHE_ROOT:-${SCRATCH_ROOT}/cache}}"
KB_ROOT="${KB_ROOT:-${HPC_KB_ROOT:-${SCRATCH_ROOT}/kb}}"

VENV_DIR="$(resolve_path "${VENV_DIR}")"
RESULTS_ROOT="$(resolve_path "${RESULTS_ROOT}")"
MODELS_DIR="$(resolve_path "${MODELS_DIR}")"
CACHE_ROOT="$(resolve_path "${CACHE_ROOT}")"
KB_ROOT="$(resolve_path "${KB_ROOT}")"

# Existing paths.env values can override the generated byproduct roots.
OUTPUT_DATA_PATH="${FTM_OUTPUT_DATA_PATH:-${OUTPUT_DATA_PATH:-${RESULTS_ROOT}/outputs}}"
OUTPUT_MODEL_PATH="${FTM_OUTPUT_MODEL_PATH:-${OUTPUT_MODEL_PATH:-${OUTPUT_DATA_PATH}}}"
AGGREGATE_PATH="${FTM_RESULTS_PATH:-${RESULTS_PATH:-${RESULTS_ROOT}/aggregate}}"
MODEL_CACHE_PATH="${FTM_CACHE_PATH:-${CACHE_PATH:-${MODELS_DIR}}}"
PACKAGES_PATH="${FTM_PACKAGES_PATH:-${RESULTS_ROOT}/packages}"

OUTPUT_DATA_PATH="$(resolve_path "${OUTPUT_DATA_PATH}")"
OUTPUT_MODEL_PATH="$(resolve_path "${OUTPUT_MODEL_PATH}")"
AGGREGATE_PATH="$(resolve_path "${AGGREGATE_PATH}")"
MODEL_CACHE_PATH="$(resolve_path "${MODEL_CACHE_PATH}")"
PACKAGES_PATH="$(resolve_path "${PACKAGES_PATH}")"

assert_safe_output() {
  local label="$1" path="$2"
  [[ "${ALLOW_REPO_OUTPUTS:-0}" == "1" ]] && return 0
  local resolved="$path"
  if command -v realpath >/dev/null 2>&1; then
    resolved="$(realpath -m -- "$path")"
  fi
  case "$resolved" in
    "${PROJECT_ROOT}"|"${PROJECT_ROOT}"/*)
      echo "ERROR: $label resolves inside repository: $resolved" >&2
      echo "       Set an external SCRATCH_ROOT or ALLOW_REPO_OUTPUTS=1 intentionally." >&2
      exit 1
      ;;
  esac
}

for pair in \
  "VENV_DIR:${VENV_DIR}" \
  "RESULTS_ROOT:${RESULTS_ROOT}" \
  "MODELS_DIR:${MODELS_DIR}" \
  "CACHE_ROOT:${CACHE_ROOT}" \
  "KB_ROOT:${KB_ROOT}" \
  "OUTPUT_DATA_PATH:${OUTPUT_DATA_PATH}" \
  "OUTPUT_MODEL_PATH:${OUTPUT_MODEL_PATH}" \
  "AGGREGATE_PATH:${AGGREGATE_PATH}" \
  "MODEL_CACHE_PATH:${MODEL_CACHE_PATH}" \
  "PACKAGES_PATH:${PACKAGES_PATH}"; do
  assert_safe_output "${pair%%:*}" "${pair#*:}"
done

command -v "${PYTHON_BIN}" >/dev/null 2>&1 || {
  echo "ERROR: ${PYTHON_BIN} not found." >&2
  exit 1
}
"${PYTHON_BIN}" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 11) else 1)' || {
  echo "ERROR: Python >= 3.11 required." >&2
  exit 1
}

echo "=== FineTuningMaster HPC setup ==="
echo "  project root : ${PROJECT_ROOT}"
echo "  scratch root : ${SCRATCH_ROOT}"
echo "  python       : ${PYTHON_BIN}"
echo "  venv         : ${VENV_DIR}"
echo "  models       : ${MODELS_DIR}"
echo "  cache        : ${CACHE_ROOT}"
echo "  KB           : ${KB_ROOT}"
echo "  outputs      : ${OUTPUT_DATA_PATH}"
echo "  aggregate    : ${AGGREGATE_PATH}"
echo "  torch index  : ${TORCH_CUDA_INDEX}"

mkdir -p \
  "${VENV_DIR}" \
  "${RESULTS_ROOT}/logs" \
  "${MODELS_DIR}" \
  "${KB_ROOT}" \
  "${OUTPUT_DATA_PATH}" \
  "${OUTPUT_MODEL_PATH}" \
  "${AGGREGATE_PATH}" \
  "${PACKAGES_PATH}" \
  "${CACHE_ROOT}/hf_home" \
  "${CACHE_ROOT}/hf_datasets" \
  "${CACHE_ROOT}/torch" \
  "${CACHE_ROOT}/xdg" \
  "${CACHE_ROOT}/mpl" \
  "${CACHE_ROOT}/pip" \
  "${CACHE_ROOT}/tmp" \
  "${CACHE_ROOT}/pycache" \
  "${CACHE_ROOT}/triton" \
  "${CACHE_ROOT}/torchinductor" \
  "${CACHE_ROOT}/cuda"

ENV_FILE="${FTM_ENV_FILE:-${HPC_ENV_FILE:-${SCRATCH_ROOT}/hpc_env.sh}}"
ENV_FILE="$(resolve_path "${ENV_FILE}")"
mkdir -p "$(dirname "${ENV_FILE}")"

cat > "${ENV_FILE}" <<EOF
# Generated by setup_hpc.sh; do not commit.
export FTM_PROJECT_ROOT="${PROJECT_ROOT}"
export FTM_SCRATCH_ROOT="${SCRATCH_ROOT}"
export FTM_ENV_FILE="${ENV_FILE}"
export HPC_ENV_FILE="${ENV_FILE}"
export FTM_VENV_DIR="${VENV_DIR}"
export FTM_RESULTS_ROOT="${RESULTS_ROOT}"
export FTM_MODELS_DIR="${MODELS_DIR}"
export FTM_CACHE_ROOT="${CACHE_ROOT}"
export FTM_KB_ROOT="${KB_ROOT}"
export FTM_KB_CHUNKS_PATH="${KB_ROOT}/chunks.jsonl"
export FTM_OUTPUT_DATA_PATH="${OUTPUT_DATA_PATH}"
export FTM_OUTPUT_MODEL_PATH="${OUTPUT_MODEL_PATH}"
export FTM_RESULTS_PATH="${AGGREGATE_PATH}"
export FTM_CACHE_PATH="${MODEL_CACHE_PATH}"
export FTM_PACKAGES_PATH="${PACKAGES_PATH}"
export TORCH_CUDA_INDEX="${TORCH_CUDA_INDEX}"
export CUDA_DEVICE_ORDER=PCI_BUS_ID
export TOKENIZERS_PARALLELISM=false

export PYTHONNOUSERSITE=1
export PYTHONPATH="${PROJECT_ROOT}/src:\${PYTHONPATH:-}"
export PYTHONPYCACHEPREFIX="${CACHE_ROOT}/pycache"
export PYTHONDONTWRITEBYTECODE=1
export HF_HOME="${CACHE_ROOT}/hf_home"
export HUGGINGFACE_HUB_CACHE="${MODEL_CACHE_PATH}"
export HF_HUB_CACHE="${MODEL_CACHE_PATH}"
export TRANSFORMERS_CACHE="${MODEL_CACHE_PATH}"
export HF_DATASETS_CACHE="${CACHE_ROOT}/hf_datasets"
export TORCH_HOME="${CACHE_ROOT}/torch"
export XDG_CACHE_HOME="${CACHE_ROOT}/xdg"
export PIP_CACHE_DIR="${CACHE_ROOT}/pip"
export MPLCONFIGDIR="${CACHE_ROOT}/mpl"
export TMPDIR="${CACHE_ROOT}/tmp"
export TEMP="${CACHE_ROOT}/tmp"
export TMP="${CACHE_ROOT}/tmp"
export TRITON_CACHE_DIR="${CACHE_ROOT}/triton"
export TRITON_HOME="${CACHE_ROOT}/triton"
export TORCHINDUCTOR_CACHE_DIR="${CACHE_ROOT}/torchinductor"
export CUDA_CACHE_PATH="${CACHE_ROOT}/cuda"
EOF
echo "  env file     : ${ENV_FILE}"

# shellcheck disable=SC1090
source "${ENV_FILE}"
source "${FTM_VENV_DIR}/bin/activate" 2>/dev/null || true

if [[ ! -x "${FTM_VENV_DIR}/bin/python" ]]; then
  echo ">>> Creating virtual environment"
  "${PYTHON_BIN}" -m venv "${FTM_VENV_DIR}"
fi
# shellcheck disable=SC1091
source "${FTM_VENV_DIR}/bin/activate"

python -m pip install --upgrade pip setuptools wheel

echo ">>> Installing CUDA PyTorch (${TORCH_CUDA_INDEX})"
python -m pip install torch==2.6.0 \
  --index-url "https://download.pytorch.org/whl/${TORCH_CUDA_INDEX}"

echo ">>> Installing training requirements"
python -m pip install -r "${PROJECT_ROOT}/requirements-train.txt"
python -m pip install -e "${PROJECT_ROOT}"

if [[ "${SKIP_KB}" -eq 0 ]]; then
  echo ">>> Building RAG knowledge base"
  python "${PROJECT_ROOT}/experiments/scripts/build_kb.py" \
    --guidelines-dir "${PROJECT_ROOT}/data/knowledge_base/guidelines" \
    --out "${FTM_KB_CHUNKS_PATH}" \
    --manifest "${FTM_KB_ROOT}/kb_manifest.json"
else
  echo ">>> Skipping KB build"
fi

if [[ "${SKIP_PREFLIGHT}" -eq 0 ]]; then
  echo ">>> Running release preflight"
  python "${PROJECT_ROOT}/experiments/scripts/check_experiment_release.py" \
    --profile final --all-models --dataset dashboard_v4 \
    --output-root "${FTM_OUTPUT_DATA_PATH}" \
    --kb-chunks-path "${FTM_KB_CHUNKS_PATH}"
else
  echo ">>> Skipping release preflight"
fi

echo
echo "=== Setup complete ==="
echo "  source ${ENV_FILE}"
echo "  sbatch experiments/slurm/job_final_matrix.sh"
